/**
 * @license
 * Copyright 2026 AionUi (aionui.com)
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Installs the generated `project-agent` skill into the backend's
 * `user_skills_dir` (discovered through the existing `/api/skills/paths`
 * endpoint). The SKILL.md content is generated by the same rule source as the
 * mission prompt, so there is a single canonical rule text.
 *
 * Installation is best-effort by design: the mission prompt already carries the
 * rules inline, so a skill-install failure must never block a mission. Callers
 * that care about the outcome can read the returned status.
 */

import { ipcBridge } from '@/common';
import { PROJECT_AGENT_SKILL_NAME } from './constants';
import { buildProjectAgentSkillMarkdown } from './missionPrompt';

export type SkillInstallStatus = 'installed' | 'unavailable';

/** Install (or refresh) the project-agent skill. Never throws. */
export async function ensureProjectAgentSkillInstalled(): Promise<SkillInstallStatus> {
  try {
    const paths = await ipcBridge.fs.getSkillPaths.invoke();
    const userSkillsDir = paths.user_skills_dir;
    if (!userSkillsDir) return 'unavailable';

    const separator = userSkillsDir.includes('\\') ? '\\' : '/';
    const skillFilePath = [userSkillsDir.replace(/[\\/]+$/, ''), PROJECT_AGENT_SKILL_NAME, 'SKILL.md'].join(separator);

    await ipcBridge.fs.writeFile.invoke({ path: skillFilePath, data: buildProjectAgentSkillMarkdown() });
    return 'installed';
  } catch (error) {
    console.warn('[ProjectAgent] skill install skipped:', error);
    return 'unavailable';
  }
}
